//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TERMINALES
    {
        public decimal ID_TERMINAL { get; set; }
        public Nullable<decimal> ID_FAB { get; set; }
        public Nullable<decimal> ID_ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA_FABRICACION { get; set; }
        public Nullable<System.DateTime> FECHA_ESTADO { get; set; }
        public string TERMINAL_DESC { get; set; }
        public string TERMINAL_NAME { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        public virtual FABRICANTES FABRICANTES { get; set; }
    }
}
